// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Result
	//	*AgentMessage_FileAck
	//	*AgentMessage_FileData
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetFileAck() *FileChunkAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileAck); ok {
			return x.FileAck
		}
	}
	return nil
}

func (x *AgentMessage) GetFileData() *FileChunkData {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileData); ok {
			return x.FileData
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // 注册
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"` // 心跳
}

type AgentMessage_Result struct {
	Result *TaskResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"` // 任务结果回报
}

type AgentMessage_FileAck struct {
	FileAck *FileChunkAck `protobuf:"bytes,4,opt,name=file_ack,json=fileAck,proto3,oneof"` // 文件下发分片确认（断点续传）
}

type AgentMessage_FileData struct {
	FileData *FileChunkData `protobuf:"bytes,5,opt,name=file_data,json=fileData,proto3,oneof"` // 文件拉取的分片数据（Agent -> Server）
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Result) isAgentMessage_Payload() {}

func (*AgentMessage_FileAck) isAgentMessage_Payload() {}

func (*AgentMessage_FileData) isAgentMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_Execute
	//	*ServerMessage_PushFile
	//	*ServerMessage_Ping
	//	*ServerMessage_PullFile
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetExecute() *ExecuteTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

func (x *ServerMessage) GetPushFile() *PushFileTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PushFile); ok {
			return x.PushFile
		}
	}
	return nil
}

func (x *ServerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerMessage) GetPullFile() *PullFileTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PullFile); ok {
			return x.PullFile
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"` // 注册确认
}

type ServerMessage_Execute struct {
	Execute *ExecuteTask `protobuf:"bytes,2,opt,name=execute,proto3,oneof"` // 执行命令/脚本
}

type ServerMessage_PushFile struct {
	PushFile *PushFileTask `protobuf:"bytes,3,opt,name=push_file,json=pushFile,proto3,oneof"` // 文件下发（分片）
}

type ServerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"` // 心跳探测
}

type ServerMessage_PullFile struct {
	PullFile *PullFileTask `protobuf:"bytes,5,opt,name=pull_file,json=pullFile,proto3,oneof"` // 文件拉取（请求 Agent 上传指定路径文件）
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_Execute) isServerMessage_Payload() {}

func (*ServerMessage_PushFile) isServerMessage_Payload() {}

func (*ServerMessage_Ping) isServerMessage_Payload() {}

func (*ServerMessage_PullFile) isServerMessage_Payload() {}

// Register 注册请求（Agent -> Server）。
type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                           // 认证 token
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                     // 主机名
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                       // Agent 版本
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                 // 操作系统，如 linux
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`                             // 架构，如 amd64 / arm64
	PanelPort     int32                  `protobuf:"varint,6,opt,name=panel_port,json=panelPort,proto3" json:"panel_port,omitempty"` // 面板 Web 端口（默认 8888，用户可改，用于 OpsAnt 免认证跳转）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Register) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Register) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Register) GetPanelPort() int32 {
	if x != nil {
		return x.PanelPort
	}
	return 0
}

// RegisterAck 注册确认（Server -> Agent）。
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Server 分配的 Agent ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterAck) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Heartbeat 心跳（Agent -> Server）。
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Ping 心跳探测（Server -> Agent）。
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ExecuteTask 执行命令/脚本任务（Server -> Agent）。
type ExecuteTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ExecuteTask_Command
	//	*ExecuteTask_Script
	Kind          isExecuteTask_Kind `protobuf_oneof:"kind"`
	Timeout       int32              `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // 超时（秒），<=0 使用默认值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTask) Reset() {
	*x = ExecuteTask{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTask) ProtoMessage() {}

func (x *ExecuteTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTask.ProtoReflect.Descriptor instead.
func (*ExecuteTask) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteTask) GetKind() isExecuteTask_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ExecuteTask) GetCommand() *CommandSpec {
	if x != nil {
		if x, ok := x.Kind.(*ExecuteTask_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ExecuteTask) GetScript() *ScriptSpec {
	if x != nil {
		if x, ok := x.Kind.(*ExecuteTask_Script); ok {
			return x.Script
		}
	}
	return nil
}

func (x *ExecuteTask) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type isExecuteTask_Kind interface {
	isExecuteTask_Kind()
}

type ExecuteTask_Command struct {
	Command *CommandSpec `protobuf:"bytes,2,opt,name=command,proto3,oneof"` // 执行命令
}

type ExecuteTask_Script struct {
	Script *ScriptSpec `protobuf:"bytes,3,opt,name=script,proto3,oneof"` // 执行脚本
}

func (*ExecuteTask_Command) isExecuteTask_Kind() {}

func (*ExecuteTask_Script) isExecuteTask_Kind() {}

// CommandSpec 命令执行参数。
type CommandSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // 命令行（sh -c 执行）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CommandSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// ScriptSpec 脚本执行参数。
type ScriptSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`     // 脚本内容
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // shell | python
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptSpec) Reset() {
	*x = ScriptSpec{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptSpec) ProtoMessage() {}

func (x *ScriptSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptSpec.ProtoReflect.Descriptor instead.
func (*ScriptSpec) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ScriptSpec) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ScriptSpec) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// PushFileTask 文件分发任务（Server -> Agent），分片传输。
// Server 按序发送多个分片（offset 递增），Agent 收到 last 分片后校验 md5 并回报 FileChunkAck。
type PushFileTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`         // 目标绝对路径（文件=重命名到该路径；目录=放入该目录并保留原文件名）
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`         // 权限（octal 字符串，如 "0755"），空则默认 0644
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`        // 文件总大小
	Md5           string                 `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`           // 整文件 MD5
	Offset        int64                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`    // 分片偏移（断点续传：Agent 回报已接收字节数，Server 从该处续传）
	Chunk         []byte                 `protobuf:"bytes,7,opt,name=chunk,proto3" json:"chunk,omitempty"`       // 分片数据
	Last          bool                   `protobuf:"varint,8,opt,name=last,proto3" json:"last,omitempty"`        // 是否最后一个分片
	Filename      string                 `protobuf:"bytes,9,opt,name=filename,proto3" json:"filename,omitempty"` // 原文件名（path 为目录时，拼接 filename 作为最终文件名）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFileTask) Reset() {
	*x = PushFileTask{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFileTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileTask) ProtoMessage() {}

func (x *PushFileTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileTask.ProtoReflect.Descriptor instead.
func (*PushFileTask) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *PushFileTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PushFileTask) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushFileTask) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PushFileTask) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PushFileTask) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *PushFileTask) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PushFileTask) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *PushFileTask) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *PushFileTask) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// FileChunkAck 文件分片确认（Agent -> Server），用于断点续传。
type FileChunkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Received      int64                  `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"` // 已接收字节数
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`            // 完成后整文件 MD5（仅 last 分片时有效）
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`        // 错误信息（非空表示该分片/文件失败）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunkAck) Reset() {
	*x = FileChunkAck{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunkAck) ProtoMessage() {}

func (x *FileChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunkAck.ProtoReflect.Descriptor instead.
func (*FileChunkAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *FileChunkAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FileChunkAck) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *FileChunkAck) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FileChunkAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TaskResult 任务结果回报（Agent -> Server）。
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // success | failed | timeout | cancelled
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *TaskResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TaskResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// PullFileTask 文件拉取请求（Server -> Agent），要求 Agent 上传指定路径的文件。
type PullFileTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // 要拉取的文件的绝对路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullFileTask) Reset() {
	*x = PullFileTask{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullFileTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFileTask) ProtoMessage() {}

func (x *PullFileTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFileTask.ProtoReflect.Descriptor instead.
func (*PullFileTask) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *PullFileTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PullFileTask) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// FileChunkData 文件拉取的分片数据（Agent -> Server）。
// Agent 按序发送多个分片（offset 递增），last 分片携带 size/md5 供 Server 校验。
type FileChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`      // 源文件路径
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`     // 文件总大小（last 分片时有效，或首分片即知）
	Md5           string                 `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`        // 整文件 MD5（last 分片时有效）
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"` // 分片偏移
	Chunk         []byte                 `protobuf:"bytes,6,opt,name=chunk,proto3" json:"chunk,omitempty"`    // 分片数据
	Last          bool                   `protobuf:"varint,7,opt,name=last,proto3" json:"last,omitempty"`     // 是否最后一个分片
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`    // 错误信息（文件不存在/无权限等，非空表示失败）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunkData) Reset() {
	*x = FileChunkData{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunkData) ProtoMessage() {}

func (x *FileChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunkData.ProtoReflect.Descriptor instead.
func (*FileChunkData) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *FileChunkData) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FileChunkData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChunkData) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileChunkData) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FileChunkData) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunkData) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FileChunkData) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *FileChunkData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\bagent.v1\"\x9d\x02\n" +
	"\fAgentMessage\x120\n" +
	"\bregister\x18\x01 \x01(\v2\x12.agent.v1.RegisterH\x00R\bregister\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x12.\n" +
	"\x06result\x18\x03 \x01(\v2\x14.agent.v1.TaskResultH\x00R\x06result\x123\n" +
	"\bfile_ack\x18\x04 \x01(\v2\x16.agent.v1.FileChunkAckH\x00R\afileAck\x126\n" +
	"\tfile_data\x18\x05 \x01(\v2\x17.agent.v1.FileChunkDataH\x00R\bfileDataB\t\n" +
	"\apayload\"\x9d\x02\n" +
	"\rServerMessage\x12:\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x15.agent.v1.RegisterAckH\x00R\vregisterAck\x121\n" +
	"\aexecute\x18\x02 \x01(\v2\x15.agent.v1.ExecuteTaskH\x00R\aexecute\x125\n" +
	"\tpush_file\x18\x03 \x01(\v2\x16.agent.v1.PushFileTaskH\x00R\bpushFile\x12$\n" +
	"\x04ping\x18\x04 \x01(\v2\x0e.agent.v1.PingH\x00R\x04ping\x125\n" +
	"\tpull_file\x18\x05 \x01(\v2\x16.agent.v1.PullFileTaskH\x00R\bpullFileB\t\n" +
	"\apayload\"\x99\x01\n" +
	"\bRegister\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x1d\n" +
	"\n" +
	"panel_port\x18\x06 \x01(\x05R\tpanelPort\"R\n" +
	"\vRegisterAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"D\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xa9\x01\n" +
	"\vExecuteTask\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x121\n" +
	"\acommand\x18\x02 \x01(\v2\x15.agent.v1.CommandSpecH\x00R\acommand\x12.\n" +
	"\x06script\x18\x03 \x01(\v2\x14.agent.v1.ScriptSpecH\x00R\x06script\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeoutB\x06\n" +
	"\x04kind\"'\n" +
	"\vCommandSpec\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"@\n" +
	"\n" +
	"ScriptSpec\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"\xd1\x01\n" +
	"\fPushFileTask\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x05 \x01(\tR\x03md5\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05chunk\x18\a \x01(\fR\x05chunk\x12\x12\n" +
	"\x04last\x18\b \x01(\bR\x04last\x12\x1a\n" +
	"\bfilename\x18\t \x01(\tR\bfilename\"i\n" +
	"\fFileChunkAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\x03R\breceived\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xa9\x01\n" +
	"\n" +
	"TaskResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"9\n" +
	"\fPullFileTask\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xb8\x01\n" +
	"\rFileChunkData\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x04 \x01(\tR\x03md5\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05chunk\x18\x06 \x01(\fR\x05chunk\x12\x12\n" +
	"\x04last\x18\a \x01(\bR\x04last\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error2M\n" +
	"\fAgentService\x12=\n" +
	"\x06Stream\x12\x16.agent.v1.AgentMessage\x1a\x17.agent.v1.ServerMessage(\x010\x01B6Z4github.com/opsmini/opsmini/internal/agent/pb;agentpbb\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),  // 0: agent.v1.AgentMessage
	(*ServerMessage)(nil), // 1: agent.v1.ServerMessage
	(*Register)(nil),      // 2: agent.v1.Register
	(*RegisterAck)(nil),   // 3: agent.v1.RegisterAck
	(*Heartbeat)(nil),     // 4: agent.v1.Heartbeat
	(*Ping)(nil),          // 5: agent.v1.Ping
	(*ExecuteTask)(nil),   // 6: agent.v1.ExecuteTask
	(*CommandSpec)(nil),   // 7: agent.v1.CommandSpec
	(*ScriptSpec)(nil),    // 8: agent.v1.ScriptSpec
	(*PushFileTask)(nil),  // 9: agent.v1.PushFileTask
	(*FileChunkAck)(nil),  // 10: agent.v1.FileChunkAck
	(*TaskResult)(nil),    // 11: agent.v1.TaskResult
	(*PullFileTask)(nil),  // 12: agent.v1.PullFileTask
	(*FileChunkData)(nil), // 13: agent.v1.FileChunkData
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	2,  // 0: agent.v1.AgentMessage.register:type_name -> agent.v1.Register
	4,  // 1: agent.v1.AgentMessage.heartbeat:type_name -> agent.v1.Heartbeat
	11, // 2: agent.v1.AgentMessage.result:type_name -> agent.v1.TaskResult
	10, // 3: agent.v1.AgentMessage.file_ack:type_name -> agent.v1.FileChunkAck
	13, // 4: agent.v1.AgentMessage.file_data:type_name -> agent.v1.FileChunkData
	3,  // 5: agent.v1.ServerMessage.register_ack:type_name -> agent.v1.RegisterAck
	6,  // 6: agent.v1.ServerMessage.execute:type_name -> agent.v1.ExecuteTask
	9,  // 7: agent.v1.ServerMessage.push_file:type_name -> agent.v1.PushFileTask
	5,  // 8: agent.v1.ServerMessage.ping:type_name -> agent.v1.Ping
	12, // 9: agent.v1.ServerMessage.pull_file:type_name -> agent.v1.PullFileTask
	7,  // 10: agent.v1.ExecuteTask.command:type_name -> agent.v1.CommandSpec
	8,  // 11: agent.v1.ExecuteTask.script:type_name -> agent.v1.ScriptSpec
	0,  // 12: agent.v1.AgentService.Stream:input_type -> agent.v1.AgentMessage
	1,  // 13: agent.v1.AgentService.Stream:output_type -> agent.v1.ServerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	file_proto_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_FileAck)(nil),
		(*AgentMessage_FileData)(nil),
	}
	file_proto_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_Execute)(nil),
		(*ServerMessage_PushFile)(nil),
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_PullFile)(nil),
	}
	file_proto_agent_v1_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*ExecuteTask_Command)(nil),
		(*ExecuteTask_Script)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
