// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/agent/v1/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Stream_FullMethodName = "/agent.v1.AgentService/Stream"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService 是 Agent（被控端）与 Server（控制端）之间的 gRPC 服务。
//
// 通信模型（去 SaltStack 化，2026-09-07 定稿）：
//   - Agent 只主动 outbound 连 Server 单端口（免 SSH、穿透 NAT/防火墙）。
//   - 一条 HTTP/2 多路复用连接同时承载下发流与回传流，无需 SaltStack 式双端口。
//   - Agent 断线后指数退避重连、周期心跳；仅配置 Server 地址 + 端口 + token。
type AgentServiceClient interface {
	// Stream 是 Agent 与 Server 之间的双向流长连接。
	// Agent 主动建立连接后：先发 Register，收到 RegisterAck 后进入工作态；
	// 期间上行心跳/结果/文件确认，下行接收任务与心跳探测。
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService 是 Agent（被控端）与 Server（控制端）之间的 gRPC 服务。
//
// 通信模型（去 SaltStack 化，2026-09-07 定稿）：
//   - Agent 只主动 outbound 连 Server 单端口（免 SSH、穿透 NAT/防火墙）。
//   - 一条 HTTP/2 多路复用连接同时承载下发流与回传流，无需 SaltStack 式双端口。
//   - Agent 断线后指数退避重连、周期心跳；仅配置 Server 地址 + 端口 + token。
type AgentServiceServer interface {
	// Stream 是 Agent 与 Server 之间的双向流长连接。
	// Agent 主动建立连接后：先发 Register，收到 RegisterAck 后进入工作态；
	// 期间上行心跳/结果/文件确认，下行接收任务与心跳探测。
	Stream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Stream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Stream(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/v1/agent.proto",
}
